"""initial schema

Revision ID: 39f3d3fca716
Revises: 
Created: 2026-08-13 09:58:59.388385
"""

from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '39f3d3fca716'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('photo_url', sa.String(length=1024), nullable=True),
    sa.Column('provider', sa.Enum('GOOGLE', 'DEMO', name='authprovider', native_enum=False, length=16), nullable=False),
    sa.Column('aws_account_id', sa.String(length=12), nullable=False),
    sa.Column('seeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_firebase_uid'), ['firebase_uid'], unique=True)

    op.create_table('hosted_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('PUBLIC', 'PRIVATE', name='hostedzonetype', native_enum=False, length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('name_servers', sa.JSON(), nullable=False),
    sa.Column('vpc_id', sa.String(length=64), nullable=True),
    sa.Column('vpc_region', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_hosted_zones_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hosted_zones')),
    sa.UniqueConstraint('user_id', 'name', 'type', name='uq_zone_owner_name_type')
    )
    with op.batch_alter_table('hosted_zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hosted_zones_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_hosted_zones_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_hosted_zones_user_name', ['user_id', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_hosted_zones_zone_id'), ['zone_id'], unique=True)

    op.create_table('dns_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hosted_zone_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('A', 'AAAA', 'CAA', 'CNAME', 'MX', 'NS', 'PTR', 'SOA', 'SRV', 'TXT', name='recordtype', native_enum=False, length=8), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('routing_policy', sa.Enum('SIMPLE', 'WEIGHTED', 'LATENCY', 'FAILOVER', 'GEOLOCATION', 'MULTIVALUE', name='routingpolicy', native_enum=False, length=16), nullable=False),
    sa.Column('set_identifier', sa.String(length=128), server_default='', nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('failover_type', sa.Enum('PRIMARY', 'SECONDARY', name='failovertype', native_enum=False, length=16), nullable=True),
    sa.Column('health_check_id', sa.String(length=64), nullable=True),
    sa.Column('is_alias', sa.Boolean(), nullable=False),
    sa.Column('alias_target', sa.String(length=512), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hosted_zone_id'], ['hosted_zones.id'], name=op.f('fk_dns_records_hosted_zone_id_hosted_zones'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dns_records')),
    sa.UniqueConstraint('hosted_zone_id', 'name', 'type', 'set_identifier', name='uq_record_zone_name_type_setid')
    )
    with op.batch_alter_table('dns_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dns_records_hosted_zone_id'), ['hosted_zone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dns_records_name'), ['name'], unique=False)
        batch_op.create_index('ix_dns_records_zone_name', ['hosted_zone_id', 'name'], unique=False)
        batch_op.create_index('ix_dns_records_zone_type', ['hosted_zone_id', 'type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dns_records', schema=None) as batch_op:
        batch_op.drop_index('ix_dns_records_zone_type')
        batch_op.drop_index('ix_dns_records_zone_name')
        batch_op.drop_index(batch_op.f('ix_dns_records_name'))
        batch_op.drop_index(batch_op.f('ix_dns_records_hosted_zone_id'))

    op.drop_table('dns_records')
    with op.batch_alter_table('hosted_zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hosted_zones_zone_id'))
        batch_op.drop_index('ix_hosted_zones_user_name')
        batch_op.drop_index(batch_op.f('ix_hosted_zones_user_id'))
        batch_op.drop_index(batch_op.f('ix_hosted_zones_name'))

    op.drop_table('hosted_zones')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_firebase_uid'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
